import { Metadata } from "next";
import { Stethoscope } from "lucide-react";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Disclaimer | Codex Medicus",
  robots: { index: false, follow: true },
};

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <nav className="border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-4xl items-center px-6">
          <a href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-md bg-gold-dim">
              <Stethoscope className="h-4 w-4 text-gold" />
            </div>
            <span className="font-serif text-lg tracking-wide">Codex Medicus</span>
          </a>
        </div>
      </nav>

      <main className="flex-1 mx-auto max-w-3xl px-6 py-16">
        <article className="prose prose-sm prose-invert max-w-none prose-headings:font-serif prose-headings:tracking-tight prose-h1:text-3xl prose-h2:mt-10 prose-h2:text-xl prose-a:text-gold prose-a:underline-offset-2 prose-strong:text-foreground">
          <h1>Disclaimer</h1>
          <p className="text-muted-foreground">Last updated: March 15, 2026</p>

          <h2>Website Disclaimer</h2>
          <p>
            The information provided by HR Online Consulting LLC, doing business as ProFlow Labs AI
            and Codex Medicus (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) on this
            website and within the Codex Medicus platform is intended for general informational
            purposes only. All content is published in good faith; however, we make no
            representation or warranty of any kind regarding the accuracy, validity, or
            completeness of any information presented.
          </p>
          <p className="font-semibold uppercase tracking-wide">
            UNDER NO CIRCUMSTANCES SHALL WE BE LIABLE TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND
            RESULTING FROM YOUR USE OF THE SERVICES OR RELIANCE ON ANY INFORMATION PROVIDED
            THEREIN. YOUR USE OF THE SERVICES IS SOLELY AT YOUR OWN RISK.
          </p>

          <h2>Medical Disclaimer</h2>
          <p>
            The content provided via Codex Medicus is for informational and educational purposes
            only. It does not constitute medical advice, diagnosis, or treatment, nor is it a
            substitute for professional judgment by qualified healthcare providers.
          </p>
          <ul>
            <li>
              <strong>No doctor-patient relationship is created.</strong> Use of the Codex Medicus
              platform does not establish a physician-patient relationship between us and any
              individual patients.
            </li>
            <li>
              <strong>Professional responsibility remains with the clinician.</strong> All
              decisions regarding patient care, treatment protocols, and clinical outcomes are the
              sole responsibility of the licensed medical professional.
            </li>
            <li>
              <strong>AI-generated content.</strong> Outputs produced by Codex Medicus are
              generated by artificial intelligence models. While skills and agents are designed
              and reviewed by a physician, AI outputs may contain errors, omissions, or outdated
              information. All clinical content must be independently verified.
            </li>
            <li>
              <strong>Evidence levels may change.</strong> Medical evidence evolves. Guidelines are
              updated. Drug interactions are discovered. Codex Medicus references evidence levels
              and guidelines at the time of its last update, but cannot guarantee real-time
              accuracy.
            </li>
            <li>
              <strong>Regulatory compliance.</strong> Users are responsible for ensuring that their
              use of Codex Medicus complies with all applicable laws, regulations, and
              institutional requirements in their jurisdiction.
            </li>
          </ul>
          <p className="font-semibold uppercase tracking-wide">
            USE OF THE CODEX MEDICUS PLATFORM IS AT YOUR OWN RISK. WE EXPRESSLY DISCLAIM ALL
            LIABILITY FOR ANY CLINICAL DECISION OR PATIENT OUTCOME RESULTING FROM THE USE OF OUR
            SERVICES.
          </p>

          <h2>Educational Tool Classification</h2>
          <p>
            Codex Medicus is classified as an educational and informational tool. It is not a
            medical device as defined by the EU Medical Device Regulation (MDR 2017/745) or the
            U.S. FDA. It does not:
          </p>
          <ul>
            <li>Diagnose diseases or medical conditions</li>
            <li>Recommend specific treatments for individual patients</li>
            <li>Replace clinical judgment or professional medical consultation</li>
            <li>Access, store, or process individual patient health records</li>
          </ul>
          <p>
            Codex Medicus provides structured medical knowledge — comparable to a textbook,
            reference database, or literature search tool — enhanced by AI for faster retrieval
            and synthesis.
          </p>

          <h2>External Links Disclaimer</h2>
          <p>
            The platform may contain links to external websites, clinical guidelines, or research
            resources. These external sites are not monitored or checked by us for accuracy or
            reliability. WE DO NOT WARRANT, ENDORSE, OR GUARANTEE ANY INFORMATION PROVIDED BY
            THIRD-PARTY WEBSITES.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, HR Online Consulting LLC and its
            officers, directors, employees, and agents shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited to
            loss of profits, data, or goodwill, arising out of or in connection with your use of
            Codex Medicus, whether based on warranty, contract, tort, or any other legal theory.
          </p>

          <h2>Contact</h2>
          <p>
            If you have questions about this disclaimer, please contact us at:{" "}
            <a href="mailto:legal@proflowlabsai.com">legal@proflowlabsai.com</a>
          </p>
        </article>
      </main>
      <Footer />
    </div>
  );
}
